CREATE TABLE 'crypto' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'c_slug' TEXT DEFAULT NULL,
'c_symbol' TEXT DEFAULT NULL
);

CREATE TABLE 'history' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'c_id' INTEGER DEFAULT NULL REFERENCES 'crypto' ('id'),
'h_price' NUMERIC DEFAULT NULL,
'h_price_high' NUMERIC DEFAULT NULL,
'h_price_low' NUMERIC DEFAULT NULL,
'h_volume' NUMERIC DEFAULT NULL,
'h_date' TEXT DEFAULT NULL,
'h_timestamp' INTEGER DEFAULT NULL
);