CREATE TABLE 'crypto' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'c_slug' TEXT(20) DEFAULT NULL,
'c_symbol' TEXT(8) DEFAULT NULL
);

CREATE TABLE 'history' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'c_id' INTEGER DEFAULT NULL REFERENCES 'crypto' ('id'),
'h_price_usd' NUMERIC DEFAULT NULL,
'h_timestamp' INTEGER DEFAULT NULL
);